import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "./contexts/AuthContext";
import NavBar from "./components/NavBar/NewNavbar";
import Footer from "./components/Footer/Footer";
import MainFooter from "./components/Footer/MainFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NJOKARU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NavBar />
          <main>{children}</main>
          <MainFooter />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
